export const ROUTES = {
  DASHBOARD: '/',
  CORPORATION_DIRECTORY: '/corporation-directory',
  COMPANY_DIRECTORY: '/company-directory',
  USER_DIRECTORY: '/user-directory',
  ROLES_PERMISSIONS: '/roles-permissions',
  COACHES: '/coaches',
  BILLING_MANAGEMENT: '/billing-management',
  PLANS_PRICING: '/plans-pricing',
  INVOICES: '/invoices',
  PROMO_CODE_MANAGEMENT: '/promo-code-management',
  QUESTION_BANK: '/question-bank',
  LEARNING_LIBRARY: '/learning-library',
  SYSTEM_HEALTH: '/system-health',
  SECURITY_BASELINES: '/security-baselines',
  AUDIT_LOGS: '/audit-logs',
  MAINTENANCE: '/maintenance',
  REPORTS: '/reports',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  ADD_BSP_ASSESSMENT_INDIVIDUAL: '/company-directory/add-bsp-assessment-individual',
} as const;
